map_update_interval: 0.1  # (map update speed s. The lower the value, the higher the frequency. But larger computational load is required.)
maxUrange: 5.0            # (intercept laser range)
maxRange: 12.0            # (laser range)
sigma: 0.05
kernelSize: 1
lstep: 0.05
astep: 0.05
iterations: 1
lsigma: 0.075
ogain: 3.0
lskip: 0                  # (set as 0 which means that all laser will be processed. If the computational pressure is overwhelming, you can change it as 1)
minimumScore: 50          # (5m)，(score that measure scan matching performance. Narrow scan range in large scene can protect pose estimation from changing rapidly. It is also called minimum matching score)
                          # (It determines the confidence of laser. The higher the value, the stricter the requirements on laser matching algorithm. And laser matching is also more likely to fail and switch to odometer data)
                          # (Too low value also results in large amount of noise in the map)
srr: 0.01
srt: 0.02
str: 0.01
stt: 0.02
linearUpdate: 0.01           # (start first scanning, when robot move beyond this distance in meters )
angularUpdate: 0.0436        # (scan once, when robot rotate beyond this angle in radian)
temporalUpdate: -1.0
resampleThreshold: 0.5
particles: 100            # (it is very important. Particle amount)
xmin: -5.0
ymin: -5.0
xmax: 5.0
ymax: 5.0
delta: 0.025              # (map resolution)
llsamplerange: 0.01
llsamplestep: 0.01
lasamplerange: 0.005
lasamplestep: 0.005
